---
- name: Set hostname
  ansible.builtin.copy:
    dest: /etc/hostname
    content: |
      {{inventory_hostname}}

- name: Install generic tools for future logins (this will take some time)
  ansible.builtin.package:
    name: "{{generic_packages}}"
    state: present
  register: installed

- name: Reboot
  ansible.builtin.fail:
    msg: Now reboot, as new packages were installed, then re-run this role.
  when: installed.changed

- name: Set fish as the default shell for {{ansible_user}}
  ansible.builtin.user:
    shell: /usr/bin/fish
    name: "{{ansible_user}}"

- name: Make initial fish config
  ansible.builtin.blockinfile:
    create: yes
    path: /etc/fish/conf.d/00-via-ansible.fish
    block: |
      # Generated on {{ansible_date_time.date}} at {{ansible_date_time.time}}
      set -x fish_escape_delay_ms 200
      set -x EDITOR /usr/bin/nvim
      function d
        exa -laFag $argv
      end

- name: Make sure /etc/hosts contain host name with a proper IP address
  tags: est
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{inventory_hostname}}$"
    line: "{{ansible_all_ipv4_addresses[0]}} {{inventory_hostname}}"