---
- name: Install generic packages in preparation for future logins
  ansible.builtin.package:
    name: "{{item}}"
    state: latest
  loop:
    - python3-pip
    - neovim
    - lnav
    - bash-completion
    - fish
    - tmux
    - exa

- name: Set fish as the default shell for {{ansible_user}}
  ansible.builtin.user:
    shell: /usr/bin/fish
    name: "{{ansible_user}}"

- name: Make initial fish config
  ansible.builtin.blockinfile:
    create: yes
    path: /etc/fish/conf.d/00-via-ansible.fish
    block: |
      # Generated on {{ansible_date_time.date}} at {{ansible_date_time.time}}
      set -x fish_escape_delay_ms 200
      set -x EDITOR /usr/bin/nvim
      function d
        exa -laFag $argv
      end

- name: Make sure /etc/hosts contain host name with a proper IP address
  tags: est
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{inventory_hostname}}$"
    line: "{{ansible_all_ipv4_addresses[0]}} {{inventory_hostname}}"